In [1]:
import numpy as np


In [4]:
# Create a two square matrix 

x= np.array([[1,5,6 ],[8,5,9],[1,0,3]])

z= np.array([[12,20,-3],[5,-8,5],[6,9,17]])

print(x,'\n')
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [5]:
#Add and Subtract the matrices x and z

r_addit= x.__add__(z)
r_subit = x.__sub__(z)

print(r_addit,'\n')
print(r_subit)

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [6]:
#Multiplication 

#Piecewise= element by element 
# the two matrices have to be the exact same size 
r_pieceswise = x.__mul__(z)

# rows by coulmn 
r_multipication = x.__matmul__(z)

print( r_pieceswise,'\n')
print(r_multipication)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]


In [12]:
# x1 + y= 2 and 10x*35y=30

# Linear to matrix
# [x+y=2]
#[10x +35y=30]


# the coeffiencts from the equation
#A= [1 1
#    10 35  ]

#use the coeffiencts 

# the variables
#x= [x
#    y]



#b= [2
# 30]


A= np.array([[1,1],[10,35]])
b= np.array([[2],[30]])


In [13]:
# Verify the size of the matrix 

print('dim. of matrix A= ',A.shape)
print('dim of vector b=',b.shape)



dim. of matrix A=  (2, 2)
dim of vector b= (2, 1)


In [14]:
# Find the det of the function 
np.linalg.det(A)

25.000000000000007

In [15]:
# Finding the inverse of the matrix 

inv_A = np.linalg.inv(A)
print(inv_A)


[[ 1.4  -0.04]
 [-0.4   0.04]]


In [17]:
#Solve the equation 

sol = inv_A.dot(b)
print(sol)

[[1.6]
 [0.4]]


In [19]:
(1.6 + 0.4)
(10*1.6 + 0.4*35)

30.0