In [1]:
import numpy as np

In [8]:
# Arrays with Numpy
a = np.array([1,2,3,4])
print(type(a))

print(a.shape)
print(a[0], a[2], a[3])

a[0]=7
print(a)

<class 'numpy.ndarray'>
(4,)
1 3 4
[7 2 3 4]


In [14]:
#each bracket represents a row 
# (row,column)
b= np. array([[5,6,7],[6,4,9]])
print(b. shape)
print (b)
print(b[0,0], b[0,1],b[1,0] )

(2, 3)
[[5 6 7]
 [6 4 9]]
5 6 6


In [32]:
zero_array = np.zeros((2,2))
print(zero_array)


ones_array = np.ones((3,2))
print(ones_array)

# Why is this useful 
#used to create a matrice to futher put inputs into

full_array= np.full((3,4),5)
print(full_array)

#Identity Matrix: Used for liner math
#Square matrix- number of rows and columns are identifical 
#diaginal matrix (0,0) (1,1)(2,2)... etc. 
identity_array= np. eye(3)
print(identity_array)

random_array= np. random.random((2,2))
print(random_array)

random_array_int= np.random.randint(100,150,(2,2))
print(random_array_int)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.50701306 0.06242632]
 [0.25829955 0.05490044]]
[[113 122]
 [124 125]]


In [34]:
print(random_array_int[:,1])


[122 125]
